import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import "../styles/globals.css";
import Header from "@/components/layouts/Header";
import QueryProvider from "@/components/providers/QueryProvider";
import Footer from "@/components/layouts/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next";
import LanguageProvider from "@/components/providers/LanguageProvider";
import { DEFAULT_LOCALE, isLocale } from "@/lib/i18n";
import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const raw = cookieStore.get("locale")?.value;
  const locale = raw && isLocale(raw) ? raw : DEFAULT_LOCALE;

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LanguageProvider initialLocale={locale}>
          <QueryProvider>
            <Header />
            {children}
            <Footer />
          </QueryProvider>
        </LanguageProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
